# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.caching=true

# Fabric Properties
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.1
loader_version=0.16.10
fabric_api_version=0.112.2+1.21.4

# Mod Properties
mod_version=1.0.0
maven_group=net.cesium
archives_base_name=cesium

# Dependencies
zstd_version=1.5.6-8
lz4_version=1.8.0
netty_version=4.1.115.Final
modmenu_version=12.0.0-beta.1
